import React from 'react';
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiFramer,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiSupabase,
  SiFirebase,
  SiPrisma,
  SiGraphql,
  SiGit,
  SiGithub,
  SiGitlab,
  SiDocker,
  SiKubernetes,
  SiGooglecloud,
  SiFigma,
  SiVite,
  SiRedux,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiPython,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiPhp,
  SiLaravel,
  SiMysql,
  SiRedis,
  SiLinux,
  SiVercel,
  SiNetlify,
  SiPostman,
  SiJest,
  SiWebpack,
  SiSass,
  SiBootstrap,
  SiGo,
  SiRust,
  SiCplusplus,
  SiDotnet,
  SiSpringboot,
  SiAstro,
  SiRemix,
  SiPnpm,
  SiYarn,
  SiBun,
  SiStorybook,
  SiStripe,
  SiClerk,
  SiShadcnui
} from 'react-icons/si';
import { FaAws } from 'react-icons/fa6';
import { Code2, Palette, Layers, Sparkles } from 'lucide-react';

// Mapping normalized tech names to { icon, color }
const techMap = {
  // Frontend
  react: { icon: SiReact, color: '#00D8FE' },
  'react.js': { icon: SiReact, color: '#00D8FE' },
  'react js': { icon: SiReact, color: '#00D8FE' },
  'react native': { icon: SiReact, color: '#00D8FE' },
  next: { icon: SiNextdotjs, color: '#111111' },
  'next.js': { icon: SiNextdotjs, color: '#111111' },
  'nextjs': { icon: SiNextdotjs, color: '#111111' },
  typescript: { icon: SiTypescript, color: '#3178C6' },
  ts: { icon: SiTypescript, color: '#3178C6' },
  javascript: { icon: SiJavascript, color: '#F7DF1E' },
  js: { icon: SiJavascript, color: '#F7DF1E' },
  html: { icon: SiHtml5, color: '#E34F26' },
  html5: { icon: SiHtml5, color: '#E34F26' },
  css: { icon: SiCss, color: '#1572B6' },
  css3: { icon: SiCss, color: '#1572B6' },
  tailwind: { icon: SiTailwindcss, color: '#06B6D4' },
  'tailwind css': { icon: SiTailwindcss, color: '#06B6D4' },
  tailwindcss: { icon: SiTailwindcss, color: '#06B6D4' },
  framer: { icon: SiFramer, color: '#0055FF' },
  'framer motion': { icon: SiFramer, color: '#0055FF' },
  vue: { icon: SiVuedotjs, color: '#4FC08D' },
  'vue.js': { icon: SiVuedotjs, color: '#4FC08D' },
  svelte: { icon: SiSvelte, color: '#FF3E00' },
  angular: { icon: SiAngular, color: '#DD0031' },
  redux: { icon: SiRedux, color: '#764ABC' },
  sass: { icon: SiSass, color: '#CC6699' },
  scss: { icon: SiSass, color: '#CC6699' },
  bootstrap: { icon: SiBootstrap, color: '#7952B3' },
  astro: { icon: SiAstro, color: '#BC52EE' },
  remix: { icon: SiRemix, color: '#111111' },
  shadcn: { icon: SiShadcnui, color: '#111111' },
  'shadcn/ui': { icon: SiShadcnui, color: '#111111' },
  'shadcn ui': { icon: SiShadcnui, color: '#111111' },
  storybook: { icon: SiStorybook, color: '#FF4785' },

  // Backend & Databases
  node: { icon: SiNodedotjs, color: '#5FA04E' },
  'node.js': { icon: SiNodedotjs, color: '#5FA04E' },
  nodejs: { icon: SiNodedotjs, color: '#5FA04E' },
  express: { icon: SiExpress, color: '#333333' },
  'express.js': { icon: SiExpress, color: '#333333' },
  expressjs: { icon: SiExpress, color: '#333333' },
  postgresql: { icon: SiPostgresql, color: '#4169E1' },
  postgres: { icon: SiPostgresql, color: '#4169E1' },
  mongodb: { icon: SiMongodb, color: '#47A248' },
  mongo: { icon: SiMongodb, color: '#47A248' },
  supabase: { icon: SiSupabase, color: '#3ECF8E' },
  firebase: { icon: SiFirebase, color: '#FFCA28' },
  prisma: { icon: SiPrisma, color: '#2D3748' },
  graphql: { icon: SiGraphql, color: '#E10098' },
  python: { icon: SiPython, color: '#3776AB' },
  django: { icon: SiDjango, color: '#092E20' },
  flask: { icon: SiFlask, color: '#111111' },
  fastapi: { icon: SiFastapi, color: '#05998B' },
  php: { icon: SiPhp, color: '#777BB4' },
  laravel: { icon: SiLaravel, color: '#FF2D20' },
  mysql: { icon: SiMysql, color: '#4479A1' },
  redis: { icon: SiRedis, color: '#FF4438' },
  go: { icon: SiGo, color: '#00ADD8' },
  golang: { icon: SiGo, color: '#00ADD8' },
  rust: { icon: SiRust, color: '#111111' },
  'c++': { icon: SiCplusplus, color: '#00599C' },
  cpp: { icon: SiCplusplus, color: '#00599C' },
  dotnet: { icon: SiDotnet, color: '#512BD4' },
  '.net': { icon: SiDotnet, color: '#512BD4' },
  'spring boot': { icon: SiSpringboot, color: '#6DB33F' },
  springboot: { icon: SiSpringboot, color: '#6DB33F' },

  // Tools, Cloud & DevOps
  git: { icon: SiGit, color: '#F05032' },
  github: { icon: SiGithub, color: '#181717' },
  gitlab: { icon: SiGitlab, color: '#FC6D26' },
  docker: { icon: SiDocker, color: '#2496ED' },
  kubernetes: { icon: SiKubernetes, color: '#326CE5' },
  aws: { icon: FaAws, color: '#FF9900' },
  'amazon web services': { icon: FaAws, color: '#FF9900' },
  gcp: { icon: SiGooglecloud, color: '#4285F4' },
  'google cloud': { icon: SiGooglecloud, color: '#4285F4' },
  figma: { icon: SiFigma, color: '#F24E1E' },
  vite: { icon: SiVite, color: '#646CFF' },
  linux: { icon: SiLinux, color: '#FCC624' },
  vercel: { icon: SiVercel, color: '#111111' },
  netlify: { icon: SiNetlify, color: '#00C7B7' },
  postman: { icon: SiPostman, color: '#FF6C37' },
  jest: { icon: SiJest, color: '#C21325' },
  webpack: { icon: SiWebpack, color: '#8DD6F9' },
  bun: { icon: SiBun, color: '#FBF0DF' },
  pnpm: { icon: SiPnpm, color: '#F69220' },
  yarn: { icon: SiYarn, color: '#2C8EBB' },
  stripe: { icon: SiStripe, color: '#635BFF' },
  clerk: { icon: SiClerk, color: '#6C47FF' },

  // Design
  'ui/ux': { icon: Sparkles, color: '#F43F5E' },
  'ui-ux': { icon: Sparkles, color: '#F43F5E' },
  'ui ux': { icon: Sparkles, color: '#F43F5E' },
  'adobe xd': { icon: Layers, color: '#FF61F6' },
  xd: { icon: Layers, color: '#FF61F6' },
  photoshop: { icon: Palette, color: '#31A8FF' },
  illustrator: { icon: Palette, color: '#FF9A00' },
  canva: { icon: Palette, color: '#00C4CC' },
};

export function getTechInfo(name) {
  if (!name) return { Icon: Code2, color: '#555555' };
  const key = name.toLowerCase().trim();
  const match = techMap[key];
  if (match) {
    return { Icon: match.icon, color: match.color };
  }
  return { Icon: Code2, color: '#555555' };
}

export default function TechIcon({ name, size = 18, className = '' }) {
  const { Icon, color } = getTechInfo(name);
  return <Icon size={size} className={className} style={{ '--tech-color': color }} />;
}

